FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

# Install OS dependencies:
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    g++ gcc \
    git \
    python3 python3-dev python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies:
RUN pip install pre-commit
RUN pip install git+https://github.com/pytorch/tensordict

WORKDIR /root
COPY . /root/

# Install the project:
RUN python3 setup.py develop

RUN pre-commit install